### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Dhavalu585** [dcraven02/SeleniumWebScraper#1]
Thanks for connecting over LinkedIn.

When I run the script - I get the below erro.

"line 45, in <module>    writer.writerow(['Name', 'Job Title', 'Company', 'College', 'Location', 'URL'])TypeError: a bytes-like object is required, not 'str' "

The only change I have done is Firefox browser - the syntax I have used is below ->

driver = webdriver.Firefox (r"C:\Users\dupadhyay\Desktop\LI\SeleniumWebScraper-master\geckodriver")

**Comment by Dhavalu585** [comment]
Hi David - Please close the above request, I was able to finally run the code.

Thanks !

**Comment by dcraven02** [comment]
No problem Dhavalu585, how did you solve your issue ?

**Comment by Dhavalu585** [comment]
>           No problem Dhavalu585, how did you solve your issue ?
Hi David,

A - I used IE driver with Selenium and placed the IE exe file in the same folder.

B - Instead of using "writer = csv.writer(open(parameters.file_name, 'wb'))" , I used ... >

writer = csv.writer(open(parameters.file_name, 'w'))

opened the output file in text mode rather than binary mode.
